WIDTH=640
HEIGHT=400
BORDER_TOP=25/2
BORDER_BOTTOM=25/2
BORDER_LEFT=25/2
BORDER_RIGHT=25/2
LIMIT_TOP = BORDER_TOP
LIMIT_BOTTOM = HEIGHT - BORDER_BOTTOM
LIMIT_LEFT = BORDER_LEFT
LIMIT_RIGHT = WIDTH - BORDER_RIGHT
FIELD_HEIGHT = LIMIT_BOTTOM - BORDER_TOP
FIELD_WIDTH = LIMIT_RIGHT - BORDER_LEFT

GOAL_START = 94
GOAL_END = 299

PLAYER1_START = (BORDER_LEFT+FIELD_WIDTH*0.8,BORDER_TOP+FIELD_HEIGHT*0.5)
PLAYER2_START = (BORDER_LEFT+FIELD_WIDTH*0.2,BORDER_TOP+FIELD_HEIGHT*0.5)
playername=("Firat","Ayberk")
PLAYER_LABEL_POS = ((200,50),(400,50))
PLAYER_LABEL_COLOR = ((255,0,0),(0,0,255))

BG_PATH='airhokey.png'
MALLET_RED_PATH='puck.png'
MALLET_BLUE_PATH='puck2.png'
MALLET_MAX_SPEED=15
MALLET_ACCELERATION=0.0025
MALLET_FRICTION=0.001
MALLET_MASS=10

DISC_PATH='disk.png'
DISC_MAX_SPEED=1
DISC_FRICTION=0.0001
DISC_MASS=1
DISC_START_ANGLE=90
DISC_START_POS = (BORDER_LEFT+FIELD_WIDTH*0.5,BORDER_TOP)
DISC_START_SPEED = DISC_MAX_SPEED*0.5
